# Generated by Django 3.1.4 on 2021-01-04 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=108)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=108)),
                ('option2', models.CharField(max_length=108)),
                ('option3', models.CharField(max_length=108)),
                ('option4', models.CharField(max_length=108)),
                ('answer', models.CharField(max_length=108)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiztitle')),
            ],
        ),
    ]
