# Generated by Django 3.1.4 on 2021-01-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiztitle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiztitle'),
        ),
    ]
